spring:
  application:
    name: blogrestapi
  profiles:
    active:
      ${ENV:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9000

project:
  post:
    image: images/postImages/
  users:
    image: images/users/
